// Generated by gencpp from file roboclaw_node/Motors_currents.msg
// DO NOT EDIT!


#ifndef ROBOCLAW_NODE_MESSAGE_MOTORS_CURRENTS_H
#define ROBOCLAW_NODE_MESSAGE_MOTORS_CURRENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboclaw_node
{
template <class ContainerAllocator>
struct Motors_currents_
{
  typedef Motors_currents_<ContainerAllocator> Type;

  Motors_currents_()
    : motor1(0.0)
    , motor2(0.0)  {
    }
  Motors_currents_(const ContainerAllocator& _alloc)
    : motor1(0.0)
    , motor2(0.0)  {
  (void)_alloc;
    }



   typedef float _motor1_type;
  _motor1_type motor1;

   typedef float _motor2_type;
  _motor2_type motor2;





  typedef boost::shared_ptr< ::roboclaw_node::Motors_currents_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboclaw_node::Motors_currents_<ContainerAllocator> const> ConstPtr;

}; // struct Motors_currents_

typedef ::roboclaw_node::Motors_currents_<std::allocator<void> > Motors_currents;

typedef boost::shared_ptr< ::roboclaw_node::Motors_currents > Motors_currentsPtr;
typedef boost::shared_ptr< ::roboclaw_node::Motors_currents const> Motors_currentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboclaw_node::Motors_currents_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboclaw_node::Motors_currents_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboclaw_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboclaw_node': ['/home/dasc/Ruilin/MSR-gazebo-code/msr_ws/src/roboclaw_ros/roboclaw_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboclaw_node::Motors_currents_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboclaw_node::Motors_currents_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboclaw_node::Motors_currents_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6918c176d50f7c79727fec6589a04c7";
  }

  static const char* value(const ::roboclaw_node::Motors_currents_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6918c176d50f7c7ULL;
  static const uint64_t static_value2 = 0x9727fec6589a04c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboclaw_node/Motors_currents";
  }

  static const char* value(const ::roboclaw_node::Motors_currents_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motor1\n\
float32 motor2\n\
";
  }

  static const char* value(const ::roboclaw_node::Motors_currents_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1);
      stream.next(m.motor2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motors_currents_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboclaw_node::Motors_currents_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboclaw_node::Motors_currents_<ContainerAllocator>& v)
  {
    s << indent << "motor1: ";
    Printer<float>::stream(s, indent + "  ", v.motor1);
    s << indent << "motor2: ";
    Printer<float>::stream(s, indent + "  ", v.motor2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCLAW_NODE_MESSAGE_MOTORS_CURRENTS_H
